version: 2.1.{build}

image: Visual Studio 2017
clone_depth: 470
build_script:
  - ps: .\nuget\nuget.exe restore ASPNETWebApp.sln;
  - ps: msbuild .\ASPNETWebApp\ASPNETWebApp.csproj;

build:
  verbosity: minimal
