version: 2.1.{build}

image: Visual Studio 2017

install:
- ps: >-

    iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex;
    choco install -fy visualstudio2017buildtools --package-parameters "--includeOptional";
    choco install -fy visualstudio2017-workload-webbuildtools --package-parameters "--includeOptional";

before_build:
- ps: >-
    .\nuget\nuget.exe restore ASPNETWebApp.sln;
    msbuild .\ASPNETWebApp\ASPNETWebApp.csproj;

build:
  verbosity: minimal
