version: 2.0.{build}
install:
  - ps: iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
  - choco install -fy visualstudio2017buildtools --package-parameters "--includeOptional"
  - choco install -fy visualstudio2017-workload-webbuildtools --package-parameters "--includeOptional"

build_script:
  # Build the compiled extension
  - .\nuget\nuget.exe restore ASPNETWebApp.sln
  - msbuild .\ASPNETWebApp\ASPNETWebApp.csproj


artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*
