version: 2.1.{build}

image: Visual Studio 2015

build:
  - ps: >-
    iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex;
 - ps: >-   
    choco install -fy visualstudio2017buildtools --package-parameters "--includeOptional";
 - ps: >-
    choco install -fy visualstudio2017-workload-webbuildtools --package-parameters "--includeOptional";
  - ps: >-
    .\nuget\nuget.exe restore ASPNETWebApp.sln;
    msbuild .\ASPNETWebApp\ASPNETWebApp.csproj;
